{% set name = "GATK4" %}
{% set version = "4.5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 1
  run_exports:
     - {{ pin_subpackage('gatk4', max_pin="x") }}

requirements:
  build:
    - openjdk =17
  host:
    - r-base =3.6
    - r-gplots
    - r-ggplot2
    - r-gsalib
    - r-reshape
    - setuptools
    - python
    - git
    - git-lfs
  run:
    - openjdk =17
    - python
    - r-base =3.6
    - r-gplots
    - r-ggplot2
    - r-gsalib
    - r-reshape

test:
  commands:
    - gatk -h
    - gatk --list
    - gatk HaplotypeCaller --help
    - gatk DetermineGermlineContigPloidy --help

outputs:
  - name: gatk4
    script: build_main.sh
    requirements:
      run:
        - openjdk >=17,<18
        - python
    test:
      commands:
        - gatk -h
        - gatk --list
        - gatk HaplotypeCaller --help
        - gatk DetermineGermlineContigPloidy --help
      imports:
        - gcnvkernel
  - name: gatk4-spark
    script: build_spark.sh
    build:
      noarch: generic
    requirements:
      run:
        - openjdk >=17,<18
        - python
        - {{ pin_subpackage("gatk4", exact=True) }}
    test:
      commands:
        - gatk -h
        - gatk --list
        - gatk MarkDuplicatesSpark --help
        - gatk DetermineGermlineContigPloidy --help

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD-3-Clause
  license_family: BSD
  summary: Genome Analysis Toolkit (GATK4)
  dev_url: https://github.com/broadinstitute/gatk
