{% set name = "GATK4" %}
{% set version = "4.5.0.0" %}
{% set sha256 = "dc1a4471e8bb566397db9894ca18acbf8f40f3fc312c8fad9a8c5390c218e916" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/gatk/releases/download/{{ version }}/gatk-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: generic
  preserve_egg_dir: True
  number: 1
  run_exports:
     - {{ pin_subpackage('gatk4', max_pin="x") }}

requirements:
  run:
    - gatk4
    - gatk4-spark
    - unzip

test:
  commands:
    - gatk -h
    - gatk --list
    - gatk HaplotypeCaller --help
    - gatk DetermineGermlineContigPloidy --help

outputs:
  - name: gatk4
    script: build_main.sh
    requirements:
      build:
        - openjdk >=17,<18
        - python =3.6
      run:
        - gcnvkernel
        - tensorflow =1.15.0
    test:
      commands:
        - gatk -h
        - gatk --list
        - gatk HaplotypeCaller --help
        - gatk DetermineGermlineContigPloidy --help
  - name: gatk4-spark
    script: build_spark.sh
    build:
      noarch: generic
    requirements:
      build:
        - openjdk >=17,<18
        - python =3.6
        - {{ pin_subpackage("gatk4", exact=True) }}
      run:
        - gcnvkernel
        - tensorflow =1.15.0
    test:
      commands:
        - gatk -h
        - gatk --list
        - gatk MarkDuplicatesSpark --help
        - gatk DetermineGermlineContigPloidy --help

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD-3-Clause
  license_family: BSD
  summary: Genome Analysis Toolkit (GATK4)
  dev_url: https://github.com/broadinstitute/gatk
